jobs:
  - name: test_aws
    type: runSh
    steps:
      - IN: skylark_aws
      - IN: docspipe_gitrepo
        switch: off
      - TASK:
        - script: IN/docspipe_repo/gitRepo/test.sh
    on_success:
      - script: echo 'SUCCESS!'
    on_failure:
      - script: echo 'FAILURE!'
